# Generated by Django 4.2.29 on 2026-04-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_order_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
